// <auto-generated />
using EntityFrameworkCoreRelationSample.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EntityFrameworkCoreRelationSample.Migrations
{
    [DbContext(typeof(BlogContext))]
    partial class BlogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("EntityFrameworkCoreRelationSample.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.Property<bool>("isActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Blog");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "ブログ村1",
                            Url = "https://xxx.yyy.zzz",
                            isActive = true
                        },
                        new
                        {
                            Id = 2,
                            Title = "ブログ村2",
                            Url = "https://aaa.bbb.ccc",
                            isActive = true
                        },
                        new
                        {
                            Id = 3,
                            Title = "ブログ村3",
                            Url = "https://ddd.eee.fff",
                            isActive = false
                        });
                });

            modelBuilder.Entity("EntityFrameworkCoreRelationSample.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlogId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contents")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BlogId");

                    b.ToTable("Post");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BlogId = 1,
                            Contents = "foobar",
                            Title = "エントリ"
                        },
                        new
                        {
                            Id = 2,
                            BlogId = 1,
                            Contents = "hogehoge",
                            Title = "エントリ"
                        },
                        new
                        {
                            Id = 3,
                            BlogId = 2,
                            Contents = "piyopiyo",
                            Title = "エントリ"
                        });
                });

            modelBuilder.Entity("EntityFrameworkCoreRelationSample.Models.Post", b =>
                {
                    b.HasOne("EntityFrameworkCoreRelationSample.Models.Blog", "Blog")
                        .WithMany("Posts")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
